package actiongen

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/hapyco/dygo/internal/hookgen"
	"github.com/hapyco/dygo/internal/jobgen"
	"github.com/hapyco/dygo/internal/runnergen"
)

func TestGenerateCreatesActionRegisterAndRunner(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	result, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}
	if !result.ActionFileCreated || !result.RunnerFileWritten {
		t.Fatalf("Generate() result = %+v, want created/written files", result)
	}

	actionSource := readTestFile(t, filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go"))
	if strings.Contains(actionSource, "DO NOT EDIT") || strings.Contains(actionSource, "Code generated by dygo") {
		t.Fatalf("action source = %q, want developer-owned starter without generated ownership header", actionSource)
	}
	for _, want := range []string{
		"package actions",
		"func Register(registry dygo.EntityActionRegistry) error",
		`Name:      "lead-action"`,
		`Label:     "Lead Action"`,
		"Selection: dygo.ActionSelectionRecord",
		"func runLeadAction(ctx context.Context, call dygo.EntityActionCall) (any, error)",
		"TODO(sales/lead): implement action behavior",
	} {
		if !strings.Contains(actionSource, want) {
			t.Fatalf("action source = %q, want substring %q", actionSource, want)
		}
	}

	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	for _, want := range []string{
		runnergen.GeneratedHeader,
		`salesleadactions "example.com/acme/apps/sales/entities/lead/actions"`,
		"EntityActions: []dygo.EntityActionRegistrar{",
		"salesleadactions.Register",
	} {
		if !strings.Contains(runnerSource, want) {
			t.Fatalf("runner source = %q, want substring %q", runnerSource, want)
		}
	}

	second, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() second error = %v, want nil", err)
	}
	if second.ActionFileCreated || second.RunnerFileWritten {
		t.Fatalf("Generate() second result = %+v, want idempotent no-op", second)
	}
}

func TestGenerateDryRunDoesNotWrite(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	result, err := GenerateWithOptions(GenerateOptions{Root: root, AppName: "sales", EntityName: "lead", DryRun: true})
	if err != nil {
		t.Fatalf("GenerateWithOptions(dry-run) error = %v, want nil", err)
	}
	if result.ActionFileStatus != "would create" || result.RunnerFileStatus != "would create" {
		t.Fatalf("GenerateWithOptions(dry-run) result = %+v, want would create statuses", result)
	}
	assertPathMissing(t, filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go"))
	assertPathMissing(t, filepath.Join(root, "cmd", "dygo", "main.go"))
}

func TestGenerateReturnsUsefulLookupErrors(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	tests := []struct {
		name       string
		appName    string
		entityName string
		want       string
	}{
		{name: "unknown app", appName: "support", entityName: "lead", want: `app "support" not found`},
		{name: "unknown entity", appName: "sales", entityName: "deal", want: `entity "deal" not found in app "sales"`},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			_, err := Generate(root, tt.appName, tt.entityName)
			if err == nil {
				t.Fatal("Generate() error = nil, want lookup error")
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("Generate() error = %q, want substring %q", err.Error(), tt.want)
			}
		})
	}
}

func TestGenerateFailsSafelyForExistingActionWithoutRegister(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")
	actionPath := filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go")
	writeTestFile(t, actionPath, "package actions\n")

	_, err := Generate(root, "sales", "lead")
	if err == nil {
		t.Fatal("Generate() error = nil, want existing action error")
	}
	for _, want := range []string{"actions.go exists but does not expose Register", "dygo.EntityActionRegistry"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("Generate() error = %q, want substring %q", err.Error(), want)
		}
	}
	assertPathMissing(t, filepath.Join(root, "cmd", "dygo", "main.go"))
}

func TestGenerateFailsSafelyForCustomRunner(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")
	writeTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"), "package main\n")

	_, err := Generate(root, "sales", "lead")
	if err == nil {
		t.Fatal("Generate() error = nil, want custom runner error")
	}
	for _, want := range []string{"cmd/dygo/main.go exists and is not dygo-generated", `salesleadactions "example.com/acme/apps/sales/entities/lead/actions"`} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("Generate() error = %q, want substring %q", err.Error(), want)
		}
	}
	assertPathMissing(t, filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go"))
}

func TestGenerateUsesEntityBundleAndKebabEntityName(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead-status")

	if _, err := Generate(root, "sales", "lead-status"); err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}

	actionSource := readTestFile(t, filepath.Join(root, "apps", "sales", "entities", "lead-status", "actions", "actions.go"))
	for _, want := range []string{"func Register(registry dygo.EntityActionRegistry) error", `Name:      "lead-status-action"`, "runLeadStatusAction"} {
		if !strings.Contains(actionSource, want) {
			t.Fatalf("action source = %q, want substring %q", actionSource, want)
		}
	}
	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runnerSource, `salesleadstatusactions "example.com/acme/apps/sales/entities/lead-status/actions"`) {
		t.Fatalf("runner source = %q, want Entity action import", runnerSource)
	}
}

func TestGeneratePreservesExistingEntityActionFile(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")
	existing := `package actions

import "github.com/hapyco/dygo/pkg/dygo"

func Register(registry dygo.EntityActionRegistry) error {
	return nil
}
`
	actionPath := filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go")
	writeTestFile(t, actionPath, existing)

	result, err := Generate(root, "sales", "lead")
	if err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}
	if result.ActionFileCreated {
		t.Fatal("ActionFileCreated = true, want existing action preserved")
	}
	if got := readTestFile(t, actionPath); got != existing {
		t.Fatalf("action source changed:\n%s", got)
	}
	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if !strings.Contains(runnerSource, "salesleadactions.Register") {
		t.Fatalf("runner source = %q, want existing action registrar call", runnerSource)
	}
}

func TestGenerateForcePreservesExistingActionFile(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")
	existing := `package actions

import "github.com/hapyco/dygo/pkg/dygo"

func Register(registry dygo.EntityActionRegistry) error {
	return nil
}
`
	actionPath := filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go")
	writeTestFile(t, actionPath, existing)

	result, err := GenerateWithOptions(GenerateOptions{Root: root, AppName: "sales", EntityName: "lead", Force: true})
	if err != nil {
		t.Fatalf("GenerateWithOptions(force) error = %v, want nil", err)
	}
	if result.ActionFileStatus != "existing" {
		t.Fatalf("ActionFileStatus = %q, want existing", result.ActionFileStatus)
	}
	if got := readTestFile(t, actionPath); got != existing {
		t.Fatalf("action source changed after --force:\n%s", got)
	}
}

func TestGeneratePreservesHookAndJobRunnerWiring(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	if _, err := hookgen.Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate(hook) error = %v, want nil", err)
	}
	if _, err := jobgen.Generate(root, "sales", "send-email"); err != nil {
		t.Fatalf("Generate(job) error = %v, want nil", err)
	}
	if _, err := Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate(action) error = %v, want nil", err)
	}

	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	for _, want := range []string{
		"RecordHooks: []dygo.RecordHookRegistrar{",
		"EntityActions: []dygo.EntityActionRegistrar{",
		"Jobs: []dygo.JobRegistrar{",
		"salesleadhooks.Register",
		"salesleadactions.Register",
		`return registry.RegisterJob("sales", "send-email", salessendemailjob.Run)`,
	} {
		if !strings.Contains(runnerSource, want) {
			t.Fatalf("runner source = %q, want substring %q", runnerSource, want)
		}
	}
}

func TestHookSyncRemovesDeletedActionWiring(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	if _, err := Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate(action) error = %v, want nil", err)
	}
	if _, err := hookgen.Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate(hook) error = %v, want nil", err)
	}
	if err := os.Remove(filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go")); err != nil {
		t.Fatalf("Remove(actions.go) error = %v", err)
	}

	if _, written, err := hookgen.UpdateRunner(root); err != nil {
		t.Fatalf("UpdateRunner() error = %v, want nil", err)
	} else if !written {
		t.Fatal("UpdateRunner() written = false, want runner update after action removal")
	}

	runnerSource := readTestFile(t, filepath.Join(root, "cmd", "dygo", "main.go"))
	if strings.Contains(runnerSource, "salesleadactions") || strings.Contains(runnerSource, "EntityActions:") {
		t.Fatalf("runner source = %q, want deleted action wiring removed", runnerSource)
	}
	if !strings.Contains(runnerSource, "salesleadhooks.Register") {
		t.Fatalf("runner source = %q, want remaining hook wiring", runnerSource)
	}
}

func TestValidateReportsMissingActionRegister(t *testing.T) {
	root := newTestProject(t, "example.com/acme")
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")
	writeTestFile(t, filepath.Join(root, "apps", "sales", "entities", "lead", "actions", "actions.go"), "package actions\n")
	if _, _, err := hookgen.UpdateRunner(root); err != nil {
		t.Fatalf("UpdateRunner() error = %v, want nil", err)
	}

	problems, err := hookgen.Validate(root)
	if err != nil {
		t.Fatalf("Validate() error = %v, want nil", err)
	}
	if len(problems) == 0 {
		t.Fatal("Validate() problems = empty, want missing Register diagnostic")
	}
	joined := strings.Join(problems, "; ")
	if !strings.Contains(joined, "Entity action file must expose Register(registry dygo.EntityActionRegistry) error") {
		t.Fatalf("Validate() problems = %q, want missing Register diagnostic", joined)
	}
}

func TestGenerateOutputCompilesInProject(t *testing.T) {
	repoRoot := repositoryRoot(t)
	root := newTestProjectWithBody(t, `module example.com/acme

go 1.26.2

require github.com/hapyco/dygo v0.0.0

replace github.com/hapyco/dygo => `+filepath.ToSlash(repoRoot)+`
`)
	copyTestFile(t, filepath.Join(repoRoot, "go.sum"), filepath.Join(root, "go.sum"))
	writeTestApp(t, root, "sales")
	writeTestEntity(t, root, "sales", "lead")

	if _, err := Generate(root, "sales", "lead"); err != nil {
		t.Fatalf("Generate() error = %v, want nil", err)
	}

	runGoCommand(t, root, "mod", "tidy")
	runGoCommand(t, root, "test", "./...")
}

func newTestProject(t *testing.T, modulePath string) string {
	t.Helper()
	return newTestProjectWithBody(t, "module "+modulePath+"\n\ngo 1.26.2\n")
}

func newTestProjectWithBody(t *testing.T, goMod string) string {
	t.Helper()
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "dygo.yml"), "name: test\n")
	writeTestFile(t, filepath.Join(root, "go.mod"), goMod)
	return root
}

func writeTestApp(t *testing.T, root string, name string) {
	t.Helper()
	body := "name: " + name + "\nlabel: " + strings.ToUpper(name[:1]) + name[1:] + "\nversion: 0.1.0\n"
	writeTestFile(t, filepath.Join(root, "apps", name, "app.yml"), body)
}

func writeTestEntity(t *testing.T, root string, appName string, entityName string) {
	t.Helper()
	body := "label: " + strings.ToUpper(entityName[:1]) + entityName[1:] + "\nname:\n  strategy: random\nfields:\n  - name: title\n    label: Title\n    type: text\n"
	writeTestFile(t, filepath.Join(root, "apps", appName, "entities", entityName, entityName+".entity.yml"), body)
}

func writeTestFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", path, err)
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", path, err)
	}
	return string(data)
}

func copyTestFile(t *testing.T, source string, destination string) {
	t.Helper()
	data, err := os.ReadFile(source)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", source, err)
	}
	writeTestFile(t, destination, string(data))
}

func assertPathMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err == nil {
		t.Fatalf("%s exists, want missing", path)
	} else if !os.IsNotExist(err) {
		t.Fatalf("Stat(%s) error = %v, want missing", path, err)
	}
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	cmd := exec.Command("git", "rev-parse", "--show-toplevel")
	output, err := cmd.Output()
	if err != nil {
		t.Fatalf("git rev-parse --show-toplevel error = %v", err)
	}
	return string(bytes.TrimSpace(output))
}

func runGoCommand(t *testing.T, dir string, args ...string) {
	t.Helper()
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go %s in generated project error = %v\n%s", strings.Join(args, " "), err, string(output))
	}
}
